/**********************************
            |GROUP-06|
***********************************/

#include <stdlib.h>
#include <stdio.h>
#include <stdbool.h>
#include <time.h>
#include "parser.h"
#include "grammar.h"
#include "first_and_follow.h"

int main(int argc,char *argv[]){
	
	int option;
	while(true){
		printf("Choose an option to perform the desired task\n");
        printf("0. Exit\n");
        printf("1. Remove Comments from the source file\n");
        printf("2. Print all tokens generated by the lexer\n");
        printf("3. Print parse tree for the program\n");
        printf("4. Calculate the total time taken\n");
        printf("Enter your choice : ");
		
		scanf("%d",&option);

		switch (option)
		{
		case 0:
			break;
		case 1:
			removeComments(argv[1], argv[2]);
			break;
		case 2:
			break;
		case 3:
			break;
		case 4:
			break;
		default:
			printf("\nPlease select a valid option!\n\n");
			break;
		}

	}

	// Initialized the Hash tables for LHS and RHS of Grammar Rules.
	initializeHashTable();

	fill_grammar();

	first_and_follow_table[0] = (FIRST_AND_FOLLOW_ENTRY *)malloc(sizeof(FIRST_AND_FOLLOW_ENTRY));
	set follow_set = first_and_follow_table[0]->follow_set;
	follow_set.t[follow_set.size] = DOLLAR;


}