/**********************************
            |GROUP-06|
***********************************/

#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>

#include "first_and_follow.h"
#include "grammar.h"
#include "parser.h"

int main(int argc, char* argv[]) {
    int option;
    // while(true){
    // 	printf("Choose an option to perform the desired task\n");
    //     printf("0. Exit\n");
    //     printf("1. Remove Comments from the source file\n");
    //     printf("2. Print all tokens generated by the lexer\n");
    //     printf("3. Print parse tree for the program\n");
    //     printf("4. Calculate the total time taken\n");
    //     printf("Enter your choice : ");

    // 	scanf("%d",&option);

    // 	switch (option)
    // 	{
    // 	case 0:
    // 		exit(0);
    // 		break;
    // 	case 1:
    // 		// removeComments(argv[1], argv[2]);
    // 		break;
    // 	case 2:
    // 		break;
    // 	case 3:
    // 		break;
    // 	case 4:
    // 		break;
    // 	default:
    // 		printf("\nPlease select a valid option!\n\n");
    // 		break;
    // 	}

    // }

    // PARSER PART

    // Initialized the Hash tables for LHS and RHS of Grammar Rules.
    initializeHashTable();

    fill_grammar();
    // make sure to add <program> rule to the Grammar RULE table first.
    // Test program (start symbol)
    // Test first sets for a few key non-terminals
    sym test_sym;
    test_sym.isTerminal = false;

    test_sym.nT = program;
    set* first_program = first_set(test_sym);
    printf("FIRST(program): ");
    for (int i = 0; i < first_program->size; i++) {
        printf("%s ", Terminals[first_program->t[i]]);
    }
    printf("\n");

    // Test mainFunction
    test_sym.nT = mainFunction;
    set* first_main = first_set(test_sym);
    printf("FIRST(mainFunction): ");
    for (int i = 0; i < first_main->size; i++) {
        printf("%s ", Terminals[first_main->t[i]]);
    }
    printf("\n");

    // Test follow sets
    set* follow_program = follow_set(test_sym);
    printf("FOLLOW(program): ");
    if (follow_program) {
        for (int i = 0; i < follow_program->size; i++) {
            printf("%s ", Terminals[follow_program->t[i]]);
        }
    }
    printf("\n");
}